[generic]
ip = '127.0.0.1'
port = 3030

[openai]
endpoint = "https://api.openai.com/v1/chat/completions"
models = ["gpt-4","gpt-3.5-turbo", "gpt-3.5-turbo-1106"]
status = "https://status.openai.com/api/v2/summary.json"

[cohere]
endpoint = "https://api.cohere.ai/v1/chat"
models = ["command", "command-light", "command-nightly", "command-nightly-light"]
status = "https://status.cohere.ai/api/v2/summary.json"

[anthropic]
endpoint = "https://api.cohere.ai/v1/chat"
models = ["claude"]
status = ""
