[openai]
endpoint = "https://api.openai.com/v1/engines/davinci/completions"
models = ["gpt-3.5-turbo", "gpt-4"]

[cohere]
endpoint = "https://api.cohere.ai/v1/chat"
models = ["command", "command-light", "command-nightly", "command-nightly-light"]

[anthropic]
endpoint = "https://api.cohere.ai/v1/chat"
models = ["command", "command-light", "command-nightly", "command-nightly-light"]
